//! 对齐: `cn.hutool.core.annotation.CacheableSynthesizedAnnotationAttributeProcessor`

mod cacheable_synthesized_annotation_attribute_processor;
mod test_value_synthesized_annotation;

pub use cacheable_synthesized_annotation_attribute_processor::CacheableSynthesizedAnnotationAttributeProcessor;
pub use test_value_synthesized_annotation::TestValueSynthesizedAnnotation;
